export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';

export const REQUEST_AUTOCOMPLETE_CITY = 'REQUEST_AUTOCOMPLETE_CITY';
export const RECEIVE_AUTOCOMPLETE_CITY = 'RECEIVE_AUTOCOMPLETE_CITY';

export const ADD_CITY_TO_STORAGE = 'ADD_CITY_TO_STORAGE';
export const REQUEST_STORED_CITIES = 'REQUEST_STORED_CITIES';
export const RECEIVE_STORED_CITIES = 'RECEIVE_STORED_CITIES';
